[package]
name = "one-brc-rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
fixed = "1.24.0"
fxhash = "0.2.1"
libc = "0.2.152"
rayon = "1.8.1"

[profile.release]
opt-level = 3
# debug = true
lto = true
panic = "abort"
strip = true
incremental = false
